### ISSUE TITLE
Duplicate labels are overwritten in document store

### ISSUE THREAD

**Issue by lewtun** [nlp-with-transformers/notebooks#23]
## Information

The problem arises in chapter:

* [ ] Introduction
* [ ] Text Classification
* [ ] Transformer Anatomy
* [ ] Multilingual Named Entity Recognition
* [ ] Text Generation
* [ ] Summarization
* [x] Question Answering
* [ ] Making Transformers Efficient in Production
* [ ] Dealing with Few to No Labels
* [ ] Training Transformers from Scratch
* [ ] Future Directions

## Describe the bug

As flagged by Julian Risch from deepset, there's a small bug when creating the labels for the document store because multiple labels (ie duplicates) are being initialised with the same ID:

```python
from haystack import Label

labels = []
for i, row in dfs["test"].iterrows():
    # Metadata used for filtering in the Retriever
    meta = {"item_id": row["title"], "question_id": row["id"]}
    # Populate labels for questions with answers
    if len(row["answers.text"]):
        for answer in row["answers.text"]:
            label = Label(
                question=row["question"], answer=answer, id=i, origin=row["id"],
                meta=meta, is_correct_answer=True, is_correct_document=True,
                no_answer=False)
            labels.append(label)
    # Populate labels for questions without answers
    else:
        label = Label(
            question=row["question"], answer="", id=i, origin=row["id"],
            meta=meta, is_correct_answer=True, is_correct_document=True,
            no_answer=True)  
        labels.append(label)
```

## TODO

- [ ] Verify the bug really is a bug (I'm not 100% sure yet)
- [ ] Fix the bug if needed and update plots etc
